### ISSUE TITLE
Issue with absorbation hearts

### ISSUE THREAD

**Issue by GreenShaman** [Terrails/Health-Overlay#2]
The absorbation hearts seem to use the heart backing for the half-ghost heart.
Not really noticeable with the default graphics, but with another pack it is.
https://i.imgur.com/cOmkIQ7.png
The absorbation hearts also seem to go under the ghost hearts.

**Comment by Terrails** [comment]
Huh. I'm pretty sure I've made it so absorption renders in the 2nd row. Only regular health should render in the 1st row. I'll look into it.

**Comment by GreenShaman** [comment]
I have the mod with leveluphp, which might be what's causing it.

**Comment by Terrails** [comment]
No that shouldn't be the problem. I've just uploaded the version that should fix this. Absorption should never be rendered in the same row as health. If I tried to get around it and made it render above the ghost hearts it could get messy.
