### ISSUE TITLE
Absorption bar renders negative

### ISSUE THREAD

**Issue by sargunv** [Terrails/Health-Overlay#3]
1. Eat a golden apple
2. Take 2.5 hearts of damage
3. The absorption bar now shows -0.5 hearts of absortption. It should be bounded at zero.

![2019-05-19_13 37 20](https://user-images.githubusercontent.com/1320357/57987786-55a44980-7a3b-11e9-8b3a-4879041de18b.png)

**Comment by Terrails** [comment]
Should be fixed now, I forgot to divide by `float` instead of `int` in `MathHelper#ceil`
